CREATE TABLE BUS (ID BIGINT AUTO_INCREMENT NOT NULL, LASTUPDATED DATETIME, NAME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE ROUTE (ID BIGINT AUTO_INCREMENT NOT NULL, LASTUPDATED DATETIME, NAME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE TRAIN (ID BIGINT AUTO_INCREMENT NOT NULL, LASTUPDATED DATETIME, PRIMARY KEY (ID))
CREATE TABLE VENTRA (ID BIGINT AUTO_INCREMENT NOT NULL, LASTUPDATED DATETIME, PRIMARY KEY (ID))
